# Generated by Django 3.0 on 2020-08-10 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tournament_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tounament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='api.Player')),
                ('player_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='api.Player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tournament')),
            ],
        ),
    ]
