# Generated by Django 3.0 on 2020-08-10 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200810_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tounament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_names', to='api.Tournament'),
        ),
    ]
