# Generated by Django 3.0 on 2020-08-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200810_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='tounament',
            new_name='tournament',
        ),
    ]
